import { CommandResult } from '../types/command.js';

const SHELL_HOOK = [
  '_env_switcher_bin() {',
  '  if [ -n "$ENV_SWITCHER_BIN" ]; then',
  '    echo "$ENV_SWITCHER_BIN"',
  '    return',
  '  fi',
  '  local cmd',
  '  cmd="$( (unset -f env-switcher 2>/dev/null; type -p env-switcher) 2>/dev/null)"',
  '  if [ -n "$cmd" ] && [ -x "$cmd" ]; then',
  '    echo "$cmd"',
  '    return',
  '  fi',
  '  cmd="$( (unset -f env-switcher 2>/dev/null; command -v env-switcher) 2>/dev/null)"',
  '  if [ -n "$cmd" ] && [ -x "$cmd" ]; then',
  '    echo "$cmd"',
  '    return',
  '  fi',
  '    echo ""',
  '}',
  '',
  'env-switcher() {',
  '  local bin',
  '  if [ -n "$ENV_SWITCHER_BIN" ]; then',
  '    bin="$ENV_SWITCHER_BIN"',
  '  else',
  '    bin="$(_env_switcher_bin)"',
  '  fi',
  '  if [ -z "$bin" ] || [ ! -x "$bin" ]; then',
  '    echo "error: env-switcher not installed or not in PATH" >&2',
  '    return 1',
  '  fi',
  '  if [ "$1" = "switch" ]; then',
  '    local profile="${2:-}"',
  '    if [ -n "$profile" ]; then',
  '      # specified profile name, direct switch',
  '      local export_output',
  '      export_output="$($bin switch "$profile" 2>&1)"',
  '      if [ $? -ne 0 ]; then',
  '        echo "error: $export_output" >&2',
  '        return 1',
  '      fi',
  '      eval "$export_output"',
  '      echo "switched to: $profile"',
  '    else',
  '      # no arguments, interactive mode',
  '      if [ -t 0 ]; then',
  '        $bin switch',
  '        if [ $? -ne 0 ]; then',
  '          return 1',
  '        fi',
  '        local export_output',
  '        export_output="$($bin export --current 2>&1)"',
  '        if [ $? -ne 0 ]; then',
  '          echo "error: $export_output" >&2',
  '          return 1',
  '        fi',
  '        eval "$export_output"',
  '      else',
  '        echo "error: interactive switch requires a terminal" >&2',
  '        return 1',
  '      fi',
  '    fi',
  '  elif [ "$1" = "--pick-current" ]; then',
  '    $bin export --current',
  '  elif [ "$1" = "export" ] && [ "$2" = "--current" ]; then',
  '    $bin export --current',
  '  elif [ "$1" = "export" ]; then',
  '    shift',
  '    $bin export "$@"',
  '  else',
  '    $bin "$@"',
  '  fi',
  '}',
].join('\n');

export async function initCommand(): Promise<CommandResult> {
  return {
    success: true,
    output: SHELL_HOOK,
  };
}
